name: Merge Catalogues Daily

# 1) Allow manual triggering via the “Run workflow” button
# 2) Also run every day at 03:00 UTC
on:
  workflow_dispatch:    # ← Add this line so you get a “Run workflow” button
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install --upgrade pip requests

      - name: Run merge_catalogues.py
        run: |
          UK_URL="https://www.superprof.co.uk/catalogue_facebook.csv"
          FR_URL="https://www.superprof.fr/catalogue_facebook.csv"
          OUT="combined.csv"
          python merge_catalogues.py "$UK_URL" "$FR_URL" "$OUT"

      - name: Commit merged CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add combined.csv
          git commit -m "Daily merge: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
